#!/bin/python

import sys
import os
import twitter
import json



#	spider is a crawler for twitter
#	it uses the twitter api and keys generated by the user
#	
#	it is dependent upon the existance of [ ] files:
#		1. a file called "access_token.json" containing a json string of the user's access token



def main():

	# opens and reads user access token

	AccessToken = json.loads(open('access_token.json', 'r').read())

